# Site settings
title: Patrick H
email: patrick.t.hammons@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hamhanded.ly" # the base hostname & protocol for your site
permalink: /words/:title
twitter_username: hamhandedly
github_username:  hamhands
linkedin_username: pthammons
feedurl: http://hamhanded.ly

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
