# Site settings
title: Patrickhammons.com
email: patrick.t.hammons@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://patrickhammons.com" # the base hostname & protocol for your site
permalink: /words/:title
twitter_username: hamhandedly
github_username:  hamhands
linkedin_username: pthammons
feedurl: https://patrickhammons.com
future: true;

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
