# Site settings
title: Hamhanded.ly
email: patrick.t.hammons@gmail.com
description: >
    Hi, I’m Patrick Hammons and I'm helping make cities work better.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hamhands.github.io" # the base hostname & protocol for your site
permalink: /words/:title
twitter_username: hamhandedly
github_username:  hamhands
linkedin_username: pthammons

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
